/*
Main program of calculator example.
Simply invoke the parser generated by bison, and then display the output.
*/

#include <stdio.h>
#include "expr.h"
#include <string.h>
#include <stdlib.h>

/* Clunky: Declare the parse function generated from parser.bison */
extern int yyparse();

/* Clunky: Declare the result of the parser from parser.bison */
extern struct expr * parser_result;
extern struct expr* NodeArray[16];
extern struct KeyValuePair* pair;


extern FILE *yyin;

// Define the symbol table 
extern struct SymbolTable  symtab;


static void initialize(char* inputFileName) {

	yyin = fopen(inputFileName,"r");
        if (yyin == NULL) {
          fprintf(stderr,"Error: Could not open file %s\n",inputFileName);
          exit(-1);
        }

	
	char *outputFileName = strcat(inputFileName,".out");
	stdout = freopen(outputFileName,"w",stdout);
        if (stdout == NULL) {
          fprintf(stderr,"Error: Could not open file %s\n",outputFileName);
          exit(-1);
        }

}

static void finalize() {

    fclose(yyin);
    fclose(stdout);
    destroyHashTable(&symtab);

}

static void parseSymTab(struct expr* NodeArray[] ,  int size)
{
	//Iterate over the symbol table an evaluate the right child of 
	//each node representing the expression for each statement
	//struct expr * node_res;
	for (size_t i = 0; i < size; i++)
	{
		
			//Break out of loop if there is not after the last node has been reached
			if (NodeArray[i] == NULL)
			{
				break;
			}
			printf("parse successful: " );
			expr_print(NodeArray[i]);
			printf("\n");
			printf("evaluates to: %d\n",(int)expr_evaluate(NodeArray[i]));	
	}
}




int main( int argc, char *argv[] )
{
	char *fileName = argv[1];
	initialize( fileName);

	//Parse expressions in the nodeArray and then evaulate the final expression
	if(yyparse()==0) {
		parseSymTab(NodeArray,16);
		printf("parse successful: ");
		expr_print(parser_result);
		printf("\n");
		printf("evaluates to: %d\n",(int)expr_evaluate(parser_result));
		return 0;

		
	} else {
		printf("parse failed!\n");
		return 1;
	}
    
	finalize();
}

