/*
Main program of calculator example.
Simply invoke the parser generated by bison, and then display the output.
*/

#include <stdio.h>
#include "expr.h"
#include <string.h>
#include <stdlib.h>

/* Clunky: Declare the parse function generated from parser.bison */
extern int yyparse();

/* Clunky: Declare the result of the parser from parser.bison */
extern struct expr * parser_result;

extern FILE *yyin;

// Define the symbol table 
struct SymbolTable  symtab;


static void initialize(char* inputFileName) {

	yyin = fopen(inputFileName,"r");
        if (yyin == NULL) {
          fprintf(stderr,"Error: Could not open file %s\n",inputFileName);
          exit(-1);
        }

	
	char *outputFileName = strcat(inputFileName,".out");
	stdout = freopen(outputFileName,"w",stdout);
        if (stdout == NULL) {
          fprintf(stderr,"Error: Could not open file %s\n",outputFileName);
          exit(-1);
        }

}

static void finalize() {

    fclose(yyin);
    fclose(stdout);
    destroyHashTable(&symtab);

}



int main( int argc, char *argv[] )
{
	char *fileName = argv[1];
	initialize( fileName);
	
	if(yyparse()==0) {
		printf("parse successful: ");
		expr_print(parser_result);
		printf("\n");
		printf("evaluates to: %f\n",expr_evaluate(parser_result));
		return 0;
	} else {
		printf("parse failed!\n");
		return 1;
	}
    
	finalize();

}

